# Konfiguracja główna aplikacji Shopify
name = "Free Shipping Bar"
client_id = "7fb3c15b431478143eac521f8700d4f0"
application_url = "https://shopify-ige3.onrender.com"
embedded = true

[access_scopes]
scopes = "read_products,write_script_tags"

[auth]
redirect_urls = [
  "https://shopify-ige3.onrender.com/auth/callback"
]

[webhooks]
api_version = "2024-01"

[web]
privacy_policy_url = "https://shopify-ige3.onrender.com/views/privacy-policy.html"
terms_of_service_url = "https://shopify-ige3.onrender.com/views/terms-of-service.html"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = false
dev_store_url = "freedelivery-test.myshopify.com"
include_config_on_deploy = true
