name = "Free Shipping Bar"
type = "theme"

[[extension_points]]
target = "theme.app_embed"
module = "blocks/delivery-bar.liquid"

[[extension_points]]
target = "section"
module = "blocks/delivery-bar.liquid"